skillMetadata:
  sections:
    - name: Demo
      fields:
        - name: prompt_on_start
          type: checkbox
          label: Offer Demo
          value: "true"
        - name: demo_tts_engine
          type: text
          label: Demo User TTS Plugin
          value: ""